#! /bin/bash

f_PERL_SCRIPT="stat_watch.pl"
d_WORKING="stat_watch"

### Find out where we are and make sure that stat_watch.pl is here too
v_PROGRAMDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
v_PROGRAMNAME="$( basename "${BASH_SOURCE[0]}" )"
if [[ ! -f "$v_PROGRAMDIR"/"$f_PERL_SCRIPT" ]]; then
	echo "Cannot find \"$f_PERL_SCRIPT\". It should be located in the same directory as this file"
	exit
fi

### Here's the part for if we're running a job
if [[ "$1" == "--run" ]]; then
	f_JOB_FILE="$2"
	if [[ ! -f "$f_JOB_FILE" ]]; then
		echo "No such file"
		exit
	fi
	v_NAME="$( egrep "^\s*Name" "$f_JOB_FILE" | sed "s/^[[:blank:]]*Name[[:blank:]]*//;s/[[:blank:]]*$//" )"
	if [[ -z $v_NAME ]]; then
		echo "Cannot find name in Job file. Exiting"
		exit
	fi
	v_DIR="$( echo "$f_JOB_FILE" | rev | cut -d "/" -f2- | rev )"
	v_EXPIRE="$( egrep "^\s*Expire" "$f_JOB_FILE" | sed "s/^[[:blank:]]*Expire[[:blank:]]*//;s/[[:blank:]]*$//" )"
	if [[ -n $v_EXPIRE && $( echo "$v_EXPIRE" | egrep -c "^[0-9]+$" ) -gt 0 ]]; then
	### If the job was set to expire, see if we still need to run it
		if [[ $( date +%s ) -gt $v_EXPIRE ]]; then
			if [[ $( date --date="now - 15 days" +%s ) -gt $v_EXPIRE ]]; then
			### If we're 15 days past expiration, delete everything
				rm -f "$v_DIR"/"$v_NAME"_files.txt "$v_DIR"/"$v_NAME"_files2.txt "$v_DIR"/"$v_NAME"_changes_*.txt "$v_DIR"/"$v_NAME"_mesasage.txt
				rm -rf "$v_DIR"/backup_"$v_NAME"
				rm -f "$f_JOB_FILE"
			fi
			exit
		fi
	fi
	### Find the perl binary to use
	if [[ -e /usr/local/cpanel/3rdparty/bin/perl ]]; then
		f_PERL_BIN="/usr/local/cpanel/3rdparty/bin/perl"
	else
		### On cPanel CentOS6 servers, it's likely that this version of perl will not have some of the right modules
		f_PERL_BIN="/usr/bin/perl"
	fi
	if [[ ! -f "$v_DIR"/"$v_NAME"_files.txt ]]; then
	### If this is the first run, do an initial backup of files
		"$f_PERL_BIN" "$v_PROGRAMDIR"/"$f_PERL_SCRIPT" --record -i "$f_JOB_FILE" -o "$v_DIR"/"$v_NAME"_files.txt -v 2> /dev/null
		"$f_PERL_BIN" "$v_PROGRAMDIR"/"$f_PERL_SCRIPT" --backup -i "$f_JOB_FILE" "$v_DIR"/"$v_NAME"_files.txt 2> /dev/null
	else
	### If this is a later run, diff the reports, and if there were changes, email them out
		"$f_PERL_BIN" "$v_PROGRAMDIR"/"$f_PERL_SCRIPT" --record -i "$f_JOB_FILE" -o "$v_DIR"/"$v_NAME"_files2.txt 2> /dev/null
		v_STAMP="$( date +%s )"
		"$f_PERL_BIN" "$v_PROGRAMDIR"/"$f_PERL_SCRIPT" --diff -i "$f_JOB_FILE" "$v_DIR"/"$v_NAME"_files.txt "$v_DIR"/"$v_NAME"_files2.txt --backup -o "$v_DIR"/"$v_NAME"_changes_"$v_STAMP".txt --format text 2> /dev/null
		if [[ $( wc -l "$v_DIR"/"$v_NAME"_changes_"$v_STAMP".txt | cut -d " " -f1 ) -lt 2 ]]; then
			rm -f "$v_DIR"/"$v_NAME"_changes_"$v_STAMP".txt
		else
		### If there were changes, check if we have an email address and then send a message to it
			v_EMAIL="$( egrep "^\s*Email" "$f_JOB_FILE" | sed "s/^[[:blank:]]*Email[[:blank:]]*//;s/[[:blank:]]*$//" )"
			if [[ -n $v_EMAIL ]]; then
				( 
					if [[ -f "$v_DIR"/"$v_NAME"_mesasage.txt ]]; then 
						cat "$v_DIR"/"$v_NAME"_mesasage.txt; 
						echo; 
					fi
					cat "$v_DIR"/"$v_NAME"_changes_"$v_STAMP".txt 
					echo
					echo "This output was generated by \"$v_PROGRAMDIR/$f_PERL_SCRIPT\" and \"$v_PROGRAMDIR/$v_PROGRAMNAME\""
				) | mail -s "stat_watch - File changes on $(hostname)" $v_EMAIL
			fi
		fi
		mv -f "$v_DIR"/"$v_NAME"_files2.txt "$v_DIR"/"$v_NAME"_files.txt
	fi
	exit
fi

### Prompt for basic details about the job that we're going to create
read -ep "What is the name of the account that you're creating a stat_watch job for? " v_ACCOUNT
if [[ $( egrep "^""$v_ACCOUNT"":" -c /etc/passwd ) -lt 1 ]]; then
	echo "Account \"$v_ACCOUNT\" Does not exist"
	exit
else
	v_HOMEDIR="$( egrep "^""$v_ACCOUNT"":" /etc/passwd | cut -d ":" -f6 )"
fi
if [[ -d "$v_HOMEDIR""/public_html" ]]; then
	read -ep "Monitor directory \"$v_HOMEDIR""/public_html\" (y/N)? " v_YN
	if [[ $( echo "$v_YN" | egrep -c "^[yY]" ) -gt 0 ]]; then
		v_MONITOR="$v_HOMEDIR""/public_html"
	fi
fi
if [[ -z $v_MONITOR ]]; then
	read -ep "Name one directory we should monitor: " v_MONITOR
	if [[ ! -e $v_MONITOR ]]; then
		echo "\"$v_MONITOR\" is not a directory"
		exit
	fi
fi
read -ep "Is there a specific name you want to use for this job (leave blank for \"$v_ACCOUNT\")? " v_NAME
if [[ -z $v_NAME ]]; then
	v_NAME="$v_ACCOUNT"
fi

### And figure out where we're going to store this job
if [[ $( stat -c %n /*/"$d_WORKING"/ 2> /dev/null | wc -l ) -gt 0 ]]; then
	echo "There are currently stat_watch working directories in the following locations:"
	stat -c %n /*/"$d_WORKING"/ 2> /dev/null | sed "s/^/   /"
	echo
fi
read -ep "What root-level directory do you want backups to be placed on? " v_PART
if [[ ! -d "$v_PART" ]]; then
	if [[ -d "/""$v_PART" ]]; then
		v_PART="/""$v_PART"
	else
		echo "\"$v_PART\" Is not a root-level directory"
		exit
	fi
fi
if [[ -f "$v_PART"/"$d_WORKING"/"$v_ACCOUNT"/"$v_NAME".job ]]; then
	echo "There already appears to be a stat_watch job at \""$v_PART"/"$d_WORKING"/"$v_ACCOUNT"/"$v_NAME".job\". You can delete or modify that."
	exit
fi

### Prompt if the job should stop running after 45 days
read -ep "Do you want this job to stop running after 45 days, and for all backed up files to be removed after 60 days (Y/n)? " v_YN
if [[ $( echo "$v_YN" | egrep -c "^[nN]" ) -eq 0 ]]; then
	v_EXPIRE=true
fi

### Prompt for an email address to send reports to
read -ep "What email address should reports be sent to (leave blank for none)? " v_EMAIL
if [[ -n $v_EMAIL ]]; then
	echo "If $v_EMAIL is a customer-facing address, MAKE SURE that appropriate expectations have been set for how these emails will be followed up on."
	echo "Here is an example of setting such expectations: " ##### I need to actually create this
	echo
	echo "Note: If you create a file at \"$v_PART/$d_WORKING/$v_ACCOUNT/$v_NAME""_message.txt, the contents of that file will be sent at the top of each email message. It might be wise to set expectations there as well"
	echo
	### Pause here, because I SUPER want people to read this
	sleep 10
fi

### Create the relevant files
mkdir -p "$v_PART"/"$d_WORKING"/"$v_ACCOUNT"/backup_"$v_NAME"
touch $v_PART/"$d_WORKING"/$v_ACCOUNT/$v_NAME.log
cat << EOF > "$v_PART"/"$d_WORKING"/"$v_ACCOUNT"/"$v_NAME".job
I $v_MONITOR
BackupD $v_PART/$d_WORKING/$v_ACCOUNT/backup_$v_NAME
BackupR \.(p(hp(4|5|7)?|[lym])|js|css|ht(ml|access)|sh)$
BackupMD 7
BackupMC 4
Log $v_PART/$d_WORKING/$v_ACCOUNT/$v_NAME.log

### These lines added by $v_PROGRAMNAME
Name $v_NAME
EOF
if [[ -n $v_EMAIL ]]; then
	echo "Email $v_EMAIL" >> "$v_PART/$d_WORKING/$v_ACCOUNT/$v_NAME.job"
fi
if [[ $v_EXPIRE == true ]]; then
	echo "Expire $( date --date="now + 45 days" +%s )" >> "$v_PART"/"$d_WORKING"/"$v_ACCOUNT"/"$v_NAME".job
fi

### Output text telling the user what next steps they need to take
echo
echo "A job file has been created at \"$v_PART/$d_WORKING/$v_ACCOUNT/$v_ACCOUNT.job\""
echo "Run \"$v_PROGRAMDIR/$f_PERL_SCRIPT --help\" for further information on how it can be edited to suit your needs"
echo "Once you have that file organized as you need it, run the following command:"
echo
echo "$v_PROGRAMDIR/$v_PROGRAMNAME --run $v_PART/$d_WORKING/$v_ACCOUNT/$v_ACCOUNT.job"
echo
echo "Then add the following line to root's crontab (adjusting times if necessary):"
echo
echo "$((RANDOM % 59)) */2 * * * $v_PROGRAMDIR/$v_PROGRAMNAME --run $v_PART/$d_WORKING/$v_ACCOUNT/$v_ACCOUNT.job > /dev/null 2>&1"
echo
